import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api, type RouterOutputs } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <img
        className="h-14 w-14 rounded-full"
        src={user.profileImageUrl}
        alt="Profile image"
      />
      <input
        className="grow bg-transparent outline-none"
        type="text"
        placeholder="Type some emojis!"
      />
    </div>
  );
};

type PostViewProps = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostViewProps) => {
  const { post, author } = props;

  return (
    <div className="flex gap-3 border-b border-slate-400 p-4">
      <img
        className="h-14 w-14 rounded-full"
        src={author.profileImageUrl}
        alt="Author profile image"
      />
      <div className="flex flex-col">
        <div className="text-slate-300">
          <span className="font-bold">{`@${author.username}`}</span>
          <span className="font-thin">{` · 1 hour ago`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Chirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && <SignInButton />}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data.map((item) => (
              <PostView key={item.post.id} {...item} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
